
services:
  auth-service:
    image: cotrav-auth-service
    build:
      context: ..
      dockerfile: docker/Dockerfile.service
      args:
        SERVICE_NAME: auth-service
        PORT: 4001
    ports:
      - "4001:4001"
    env_file:
      - ../services/auth-service/.env
    environment:
      KEYCLOAK_BASE_URL: http://host.docker.internal:8080

  flight-service:
    image: cotrav-flight-service
    build:
      context: ..
      dockerfile: docker/Dockerfile.service
      args:
        SERVICE_NAME: flight-service
        PORT: 4002
    ports:
      - "4002:4002"
    env_file:
      - ../services/flight-service/.env
    environment:
      NODE_ENV: production