import type { KpiCard } from "../types/billsDashboard.types";

export const KPI_CARDS: KpiCard[] = [
  {
    title: "Total Bills",
    count: "815",
    amount: "₹ 154,118,862.54",
    tag: "Overview",
    titleClass: "text-slate-500",
    amountClass: "text-slate-500",
    tagClass: "bg-slate-100 text-slate-600",
  },
  {
    title: "Approval Pending",
    count: "86",
    amount: "₹ 5,275,087.03",
    tag: "Act Now",
    href: "/taxivaxi/all-bill/0",
    borderClass: "border-amber-300",
    titleClass: "text-amber-600",
    amountClass: "text-amber-700",
    tagClass: "bg-amber-100 text-amber-700",
    actionText: "Review & approve pending bills.",
  },
  {
    title: "Approved Bills",
    count: "15",
    amount: "₹ 1,900,357.58",
    tag: "Ready",
    href: "/taxivaxi/all-bill/1",
    borderClass: "border-sky-300",
    titleClass: "text-sky-600",
    amountClass: "text-sky-700",
    tagClass: "bg-sky-100 text-sky-700",
    actionText: "Move to payment queue.",
  },
  {
    title: "Pending Payments",
    count: "602",
    amount: "₹ 105,022,161.49",
    tag: "High",
    href: "/taxivaxi/all-bill/2",
    borderClass: "border-red-300",
    titleClass: "text-red-600",
    amountClass: "text-red-700",
    tagClass: "bg-red-100 text-red-700",
    actionText: "Prioritize payouts & resolve holds.",
  },
  {
    title: "Partial Payments",
    count: "3",
    amount: "₹ 4,312.00",
    tag: "Follow-up",
    href: "/taxivaxi/all-bill/3",
    titleClass: "text-slate-500",
    amountClass: "text-slate-500",
    tagClass: "bg-slate-100 text-slate-600",
    actionText: "Close balance & update receipts.",
  },
  {
    title: "Paid",
    count: "34",
    amount: "₹ 8,541,343.71",
    tag: "Completed",
    href: "/taxivaxi/all-bill/4",
    borderClass: "border-emerald-300",
    titleClass: "text-emerald-600",
    amountClass: "text-emerald-700",
    tagClass: "bg-emerald-100 text-emerald-700",
    actionText: "Download receipts & audit.",
  },
];