
services:
  auth-service:
    image: cotrav-auth-service
    build:
      context: ..
      dockerfile: docker/Dockerfile.service
      args:
        SERVICE_NAME: auth-service
        PORT: 4001
    ports:
      - "4001:4001"
    env_file:
      - ../services/auth-service/.env
